### ISSUE TITLE
Dillmann ኀይመት

### ISSUE THREAD

**Issue by abausi** [SChAth/dillmann#117]
there is a problem in the word division of the Latin translation in the word "cubiculum"; and the Ar. correspondent is not exactly displayed

**Comment by PietroLiuzzo** [comment]
Under the term mentioned in title I see that tabernaculum is wrong. This is a problem inherited by the source file which can be fixed by hitting the update button and editing the text. I cannot do this at the moment but I suspect the translation markup is divided. It will probably be enough to delete >  >la> in the middle of the word

**Comment by PietroLiuzzo** [comment]
>la> tabernaculum > was infact marked as `<i>taberna</i><i>culum</i>` and thus as >la> taberna > >la>culum >. I have corrected this. I was logged in as  @AndreasEllwardt for testing another issue
