### ISSUE TITLE
Syriac s.v. ብንት፡

### ISSUE THREAD

**Issue by AndreasEllwardt** [SChAth/dillmann#124]
I tried to correct a mistake in the word ܒܰܪ̱ܬܳܐ and discovered that the xml was \*syr*ܒܰܪ\*̱\*syr*ܬܳܐ\*. So, this seems to me a system error which I should rather not correct, or?

**Comment by PietroLiuzzo** [comment]
the word was split in two because it contained in the original a non syriac unicode character (underline, which in your post above is under the star). you can always retype the word with the correct markdown: \*syr*ܒܰܪܬܳܐ\* . Please note that the editor shows you NO XML at all, it was built to facilitate data entry reducing it to minimal string editing.

**Comment by AndreasEllwardt** [comment]
then, how should I call it, if I may not call it "xml"?

**Comment by PietroLiuzzo** [comment]
text? it is simply not XML. to see the xml you are editing via the text intermediate format, please, append .xml to the end of the lemma url. e.g. http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/L7830309c81194e8685a8e76d9c12a90c.xml

please close issue if the problem is not there any more.

**Comment by AndreasEllwardt** [comment]
so, the problem will be solved in retyping Syriac words containing a linea occultans?

**Comment by PietroLiuzzo** [comment]
I have found no other u0304 or u0311 instance
